services:
  postgres:
    image: postgres:17

    container_name: booking-postgres

    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: bookinguser
      POSTGRES_PASSWORD: bookingpass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: