spring:
  application:
    name: booking1

  datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb?options=-c%20timezone=Europe/Kyiv
    username: bookinguser
    password: bookingpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Europe/Kyiv